name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Nuitka Build
      run: |
        python -m nuitka --onefile --standalone --plugin-enable=streamlit --windows-disable-console --output-dir=release app.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ArchivalPRO-Executable
        path: release/app.exe
